module DocumentationCodeSnippetTest exposing (tests)

{-| automatically generated by [elm-review-documentation-code-snippet](https://dark.elm.dmy.fr/packages/lue-bird/elm-review-documentation-code-snippet/latest)
-}

import Differ
import Expect
import Test


tests : Test.Test
tests =
    Test.describe
        "documentation code snippets"
        [ Test.describe
            "readme"
            [ Test.describe
                "code snippet 0"
                [ Test.test
                    "0"
                    (\() ->
                        patchedUser__Readme_0
                            == Result.Ok newUser__Readme_0
                            |> Expect.equal Basics.True
                    )
                , Test.test
                    "1"
                    (\() ->
                        uhoh__Readme_0
                            |> Expect.equal (Result.Err Differ.MismatchedDelta)
                    )
                ]
            ]
        ]


type alias User__Readme_0 =
    { name : String.String, age : Basics.Int, hobbies : List String.String }


oldUser__Readme_0 =
    { name = "Ed", age = 44, hobbies = [ "programming", "reading" ] }


newUser__Readme_0 =
    { name = "Ed", age = 44, hobbies = [ "programming", "reading", "cricket" ] }


userDiffer__Readme_0 : Differ.Differ User__Readme_0
userDiffer__Readme_0 =
    Differ.pure User__Readme_0
        |> Differ.andMap .name Differ.string
        |> Differ.andMap .age Differ.int
        |> Differ.andMap .hobbies (Differ.list Differ.string)


delta__Readme_0 =
    Differ.run userDiffer__Readme_0 oldUser__Readme_0 newUser__Readme_0


patchedUser__Readme_0 =
    Differ.patch userDiffer__Readme_0 delta__Readme_0 oldUser__Readme_0


wrongUser__Readme_0 =
    { name = "Arthur", age = 2, hobbies = [ "gardening", "playing with toys" ] }


uhoh__Readme_0 =
    Differ.patch userDiffer__Readme_0 delta__Readme_0 wrongUser__Readme_0
